service: tire1000

frameworkVersion: "4"

provider: ${file(sls/provider.yml)}

custom: ${file(sls/custom.yml)}

package:
  individually: true

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions: ${file(sls/functions.yml)}

resources: ${file(sls/resources.yml)}
